### ISSUE TITLE
Sketch too big

### ISSUE THREAD

**Issue by sergejey** [olehs/r4sGate#3]
Привет!

Почему-то не удаётся скомпилировать скетч -- получаю ошибку Sketch uses 1560622 bytes (119%) of program storage space. Maximum is 1310720 bytes.

![ошибка](https://c2n.me/42I9bsV.png)

Может будут идеи из-за чего так происходит?

Спасибо.

**Comment by olehs** [comment]
Привет.
Скорее всего выбрана не та плата. Обычно у ESP32 4МБ флэш.
У меня вот такие настройки:
![image](https://user-images.githubusercontent.com/606709/61690354-c7e22480-ad31-11e9-82e8-e9b09295916e.png)

**Comment by sergejey** [comment]
Спасибо! Помогла смена Partition Scheme -- по-умолчанию там мало места под приложение выделяется.
