### ISSUE TITLE
AUTH_FAILED

### ISSUE THREAD

**Issue by sergejey** [olehs/r4sGate#4]
Привет,

Ещё вопросик :)
Завёл шлюз, но теперь почему-то не могу к чайнику его подключить. Как это правильно сделать?

Вижу, что в MQTT появился статус:
r4s/status: online
r4s/f4c734cb7f32/status: offline
r4s/f4c734cb7f32/error: AUTH_FAILED

Я так понимаю ошибка авторизации, но какая последовательность для привязки чайника к шлюзу?

**Comment by olehs** [comment]
Ввести чайник в режим привязки и ресетнуть плату.
Или лучше наоборот, т.к. плата еще тратит время на коннект к вайфай

**Comment by olehs** [comment]
а вообще все в первом сообщении ;)
https://mjdm.ru/forum/viewtopic.php?f=8&t=5501&p=81384

**Comment by sergejey** [comment]
Спасибо, ссылка очень пригодилась бы в readme.md :)
Но с авторизацией чё-то так и не получается -- пробовал кучу комбинаций, но то ли у меня долго к wifi соединяется, то ли ещё что.

А как вообще алгоритм устроен? Попытка авторизации происходит только при сбросе платы? Я к тому может ли быть так, что чайник выходит из режима привязки до того, как шлюз приступит к попытке авторизации. Или можно после полной загрузки и подключения ещё раз запустить привязку на чайнике и плата попытается сама привязаться снова?

**Comment by olehs** [comment]
Уже толком и не помню, т.к. сам это делал только раз в жизни))
А что в консоли пишет ?

**Comment by sergejey** [comment]
Starting Arduino R4S Gateway...

Connecting to jeyhome
..
WiFi connected
IP address: 
192.168.0.150
MDNS responder started
WebAPI server started
Attempting MQTT connection...connected
Starting device scan...
BLE Advertised Device found : Name: RK-M171S, Address: f4:c7:34:cb:7f:32, serviceUUID: 6e400001-b5a3-f393-e0a9-e50e24dcca9e
Found our device at address : f4:c7:34:cb:7f:32
 - Connecting to server with address : f4:c7:34:cb:7f:32
(тут долгая пауза)
 - BLE Device disconnected 
Failed to connect server with address : f4:c7:34:cb:7f:32
Failed to connect to the server.

и так по кругу...

**Comment by sergejey** [comment]
Ещё такой вопрос -- в readme ссылки на библиотеки, но с ESP32 они и так идут (кроме pubsub). имеет ли смысл вместо стандартных брать те что по ссылкам?

**Comment by olehs** [comment]
Судя по логу, вообще не удается подключится к чайнику. Странно, т.к. AUTH_FAILED означает, что подключение все же было в какой-то момент.

По поводу библиотек - я сильно переделывал стандартные библиотеки, т.к. они были очень сырыми. Совместимости, насколько помню, не сохранилось.

**Comment by olehs** [comment]
Я переделал скетч на Ардуино 1.8.10.
Библиотеки, которые сейчас идут с ESP32, теперь вполне рабочие и нужно использовать их.

По поводу привязки.
Последовательность такая:
1. Зажать ресет на ESP и кнопку привязки ("+") на чайнике одновременно.
2. Досчитать до 5-ти и отпустить ресет.
3. Держать "+", пока чайник не войдет в режим привязки и не просигнализирует трелью об успешном завершении.

**Comment by sergejey** [comment]
Класс! Спасибо, обязательно попробую новый скетч.

**Comment by sergejey** [comment]
Всё получилось! Спасибо огромное :)
